server.port: 8080
eureka.client.service-url.defaultZone: http://service-discovery:8761/eureka/

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db1:5432/rcsp8-db1
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        default_schema: public
        id:
          new_generator_mappings: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

weapon.service.url: http://weapon-service:8081
quest.service.url: http://quest-service:8082
  